routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminPostController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\AdminCategoryController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('/', [AdminController::class, 'index'])->name('admin.index');
    Route::resource('/users', AdminUserController::class);
    Route::resource('/posts', AdminPostController::class, [
        'as' => 'admin'
    ]);
    Route::resource('/categories', AdminCategoryController::class, [
        'as' => 'admin'
    ]);
});

Route::get('/login', [UserController::class, 'loginForm'])->name('loginForm');
Route::post('/login', [UserController::class, 'login'])->name('login');
Route::get('/register', [UserController::class, 'create'])->name('create');
Route::post('/register', [UserController::class, 'store'])->name('store');
Route::get('/logout', [UserController::class, 'logout'])->name('logout');

Route::get('/',[PostController::class, 'index'])->name('home');
Route::get('/post/{slug}',[PostController::class, 'show'])->name('post.show');
Route::get('/categories/{slug}', [CategoryController::class, 'show'])->name('categories.show');
Route::get('/categories', [CategoryController::class, 'index'])->name('categories.index');
Route::get('/about', function() {
   return view('about');
})->name('about');
Route::get('contact', [ContactController::class, 'index'])->name('contact');
Route::post('/contact/store', [ContactController::class, 'store'])->name('contact.request.store');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserCreate;
use App\Http\Requests\UserCreateRequest;
use App\Http\Requests\UserLoginRequest;
use App\Models\User;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    private $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function loginForm()
    {
        return view('login');
    }

    public function create()
    {
        return view('register');
    }

    public function store(UserCreateRequest $request)
    {
        $user = $this->userRepository->register($request->validated());
        if ($user) {
           return redirect()->route('loginForm')->with('register', 'Вы зарегистрированы');
        }
    }

    public function login(UserLoginRequest $request)
    {
        $remember = false;
        $validated  = $request->validated();
        if (!empty($validated['remember'])) {
            $remember = true;
        }

        if (Auth::attempt(['email' => $validated['email'], 'password' => $validated['password']], $remember)) {
            $request->session()->regenerate();
            session()->flash('success', 'Вы успешно авторизованы');
            if (Auth::user()->is_admin) {
                return redirect()->route('admin.index');
            }
            return redirect()->route('home');
        }

        return redirect()->back()->withErrors(['Неправильный логин или пароль']);
    }

    public function logout(Request $request)
    {
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->home();
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.layout')

@section('content')
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Создание пользователя</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a href="{{ route('users.index') }}" class="btn btn-primary">Назад</a>
                </div>
            </div>
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>

        <div class="col-lg-4">
            <form method="POST" action="{{ route('users.store') }}">
                @csrf
                <div class="mb-3">
                    <label for="exampleInputName" class="form-label">Имя</label>
                    <input name="name" type="text" class="form-control" id="exampleInputName" aria-describedby="emailHelp" value="{{ old('name') }}">
                    <div id="nameHelp" class="form-text"></div>
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email</label>
                    <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="{{ old('email') }}">
                    <div id="emailHelp" class="form-text"></div>
                    @error('email')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Пароль</label>
                    <input name="password" type="text" class="form-control" id="exampleInputPassword1">
                </div>
                @error('password')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror

                <div class="mb-3 form-check">
                    <input name="is_admin" type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Администратор</label>
                </div>
                <button type="submit" class="btn btn-primary">Создать</button>
            </form>
        </div>
    </main>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.layout')

@section('content')
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Редактирование пользователя</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a href="{{ route('users.index') }}" class="btn btn-primary">Назад</a>
                </div>
            </div>
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>

        <div class="col-lg-4">
            <form method="POST" action="{{ route('users.update', ['user' => $user->id]) }}">
                @csrf
                @method('PUT')
                <div class="mb-3">
                    <label for="exampleInputName" class="form-label">Имя</label>
                    <input name="name" type="text" class="form-control" id="exampleInputName" aria-describedby="emailHelp" value="{{ $user->name }}">
                    <div id="nameHelp" class="form-text"></div>
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email</label>
                    <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="{{ $user->email }}">
                    <div id="emailHelp" class="form-text"></div>
                    @error('email')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Пароль</label>
                    <input name="password" type="text" class="form-control" id="exampleInputPassword1">
                </div>
                @error('password')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                {{ $user->isAdmin }}
                <div class="mb-3 form-check">
                    <input name="is_admin" type="checkbox" class="form-check-input" id="exampleCheck1"  @if ($user->is_admin === 1) checked @endif>
                    <label class="form-check-label" for="exampleCheck1">Администратор</label>
                </div>
                <button type="submit" class="btn btn-primary">Редактировать</button>
            </form>
        </div>
    </main>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.layout')

@section('content')

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Пользователи</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('users.create') }}" class="btn btn-primary">Добавить пользователя</a>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Email</th>
                    <th scope="col">Админ</th>
                    <th scope="col">Дата регистрации</th>
                    <th scope="col">Действие</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->is_admin }}</td>
                        <td>{{ $user->created_at }}</td>
                        <td>
                            <a href="{{ route('users.edit', ['user' => $user->id]) }}" class="btn btn-warning">Редактировать</a>
                            <form action="{{ route('users.destroy', ['user' => $user->id]) }}" method="POST" style="display: inline">
                                @csrf
                                @method('DELETE')
{{--                                <input type="hidden" name="user_id" value="{{ $user->id }}">--}}
                                <input type="submit" class="btn btn-danger" value="Удалить">
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
                {{ $users->links('vendor.pagination.bootstrap-4') }}
        </div>
    </main>
@endsection